remote_theme: "jekyll-theme-mediumish"
plugins:
  - jekyll-remote-theme
title: Tilli Netta Saunders
description: "Mixed-Discipline Designer with a background in Mobile and F2P gaming.<br><br>Based in England, working out of London.<br><br>Looking for Level or Game Designer roles, Hybrid or Remote, London based."
